# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='prize',
            field=models.IntegerField(default=0),
        ),
    ]
