# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-06 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_code_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('ip', models.GenericIPAddressField()),
                ('clicks', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
