# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-06 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ip',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Anonymous', max_length=240),
        ),
    ]
